nginx:
  image: revive
  container_name: nginx
  ports:
    - "8080:80"
  volumes:
    - ./../app:/var/www/html
    - ./../server/nginx.conf:/etc/nginx/nginx.conf
    - ./entrypoint.sh:/usr/local/bin/entrypoint.sh